import { DEFAULT_VOICE_BY_TONE, THEMES, TRAINER_TONES, VOICE_PERSONAS, VOICE_PERSONA_LABELS } from "../core/constants.mjs";
import { escapeHtml } from "../core/utils.mjs";
import { button, icon } from "./components.mjs";

const GOALS = [
  ["build muscle","Build muscle","Progressive strength and size"],
  ["get stronger","Get stronger","Build measurable performance"],
  ["lose fat","Lose fat","Support training while changing habits"],
  ["stay consistent","Stay consistent","Make the plan survive real life"],
];
const BLOCKERS = [
  ["time","Not enough time","Schedule pressure breaks the plan"],
  ["motivation","Starting is hard","You know what to do but do not begin"],
  ["all-or-nothing","All or nothing","One miss can turn into a lost week"],
  ["uncertainty","Second-guessing","You keep changing the plan"],
];

export function renderGate(founder = "mo") {
  return `<section class="gate-screen"><div class="gate-brand"><div class="fitcoach-mark"><span>F</span><i></i></div><span class="eyebrow">SYMBIO LABS · PRIVATE FOUNDER BUILD</span><h1>Your trainer.<br><em>In your pocket.</em></h1><p>A persistent training relationship that remembers the work, adapts without judgment, and explains every change.</p></div><div class="gate-card card"><div class="privacy-callout">${icon("info")}<p><b>Low-sensitivity founder research.</b> Do not enter diagnoses, medication details, credentials, measurements, identifiers, or private records.</p></div><div class="founder-switch" role="radiogroup" aria-label="Choose founder"><button role="radio" aria-checked="${founder === "mo"}" class="${founder === "mo" ? "active" : ""}" data-action="choose-founder" data-value="mo"><span>M</span><b>Mohammed<small>Product + trainer feel</small></b></button><button role="radio" aria-checked="${founder === "ravi"}" class="${founder === "ravi" ? "active" : ""}" data-action="choose-founder" data-value="ravi"><span>R</span><b>Ravi<small>Systems + safety</small></b></button></div><label class="field"><span>Founder access code</span><input id="founder-code" type="password" autocomplete="off" placeholder="Enter code"><small id="gate-error" class="field-error" hidden>That code is not correct.</small></label>${button({label:"Enter FitCoach",action:"enter-gate",variant:"primary"})}<small class="founder-disclosure">Convenience gate only. Production authentication is not active.</small></div></section>`;
}

function goalStep(draft) {
  return `<div class="onboarding-step"><span class="eyebrow">YOUR DIRECTION</span><h1>What are we building toward?</h1><p>One clear objective helps the trainer decide what matters and what can wait.</p><div class="option-grid">${GOALS.map(([value,title,copy]) => `<button class="option-card ${draft.profile.goal === value ? "active" : ""}" data-action="onboarding-choice" data-field="goal" data-value="${value}">${icon(value === "get stronger" ? "train" : value === "stay consistent" ? "today" : "progress")}<span><b>${title}</b><small>${copy}</small></span>${icon("check","selected-mark")}</button>`).join("")}</div><div class="theme-onboarding"><span><b>Choose your starting look</b><small>You can change this any time.</small></span><div role="radiogroup" aria-label="Starting theme">${THEMES.map(value => `<button role="radio" aria-checked="${draft.settings.theme === value}" class="${draft.settings.theme === value ? "active" : ""}" data-action="onboarding-setting" data-field="theme" data-value="${value}">${value}</button>`).join("")}</div></div></div>`;
}

function scheduleStep(draft) {
  return `<div class="onboarding-step"><span class="eyebrow">REAL AVAILABILITY</span><h1>Build a week you can repeat.</h1><p>A realistic plan beats an ambitious plan that disappears when life gets busy.</p><div class="onboarding-form"><label><span>Experience</span><select data-action="onboarding-profile-field" data-field="experience">${["beginner","intermediate","advanced"].map(value => `<option ${draft.profile.experience===value?"selected":""}>${value}</option>`).join("")}</select></label><label><span>Training days</span><select data-action="onboarding-number" data-field="days">${[2,3,4,5,6].map(value=>`<option value="${value}" ${draft.profile.days===value?"selected":""}>${value} days/week</option>`).join("")}</select></label><label><span>Typical session</span><select data-action="onboarding-number" data-field="duration">${[20,30,45,60,75].map(value=>`<option value="${value}" ${draft.profile.duration===value?"selected":""}>${value} minutes</option>`).join("")}</select></label><label><span>Equipment</span><select data-action="onboarding-profile-field" data-field="equipment">${["full gym","home gym","dumbbells only","bodyweight"].map(value=>`<option ${draft.profile.equipment===value?"selected":""}>${value}</option>`).join("")}</select></label><label><span>Usual location</span><select data-action="onboarding-profile-field" data-field="location">${["gym","home","travel","outdoors"].map(value=>`<option ${draft.profile.location===value?"selected":""}>${value}</option>`).join("")}</select></label></div><div class="schedule-preview"><span>${icon("clock")}</span><p><b>${draft.profile.days} sessions · ${draft.profile.duration} minutes</b><small>Full, reduced, and minimum versions will share one plan thread.</small></p></div></div>`;
}

function relationshipStep(draft) {
  const recommendedVoice = VOICE_PERSONA_LABELS[DEFAULT_VOICE_BY_TONE[draft.profile.tone] || draft.settings.voicePersona];
  return `<div class="onboarding-step"><span class="eyebrow">THE TRAINER RELATIONSHIP</span><h1>How should your coach show up?</h1><p>Tone changes presentation only. Safety, evidence, and plan decisions stay exactly the same.</p><div class="option-grid compact">${BLOCKERS.map(([value,title,copy])=>`<button class="option-card ${draft.profile.blocker===value?"active":""}" data-action="onboarding-choice" data-field="blocker" data-value="${value}"><span><b>${title}</b><small>${copy}</small></span>${icon("check","selected-mark")}</button>`).join("")}</div><div class="onboarding-form"><label><span>Trainer tone</span><select data-action="onboarding-profile-field" data-field="tone">${TRAINER_TONES.map(value=>`<option ${draft.profile.tone===value?"selected":""}>${value}</option>`).join("")}</select></label><label><span>Premium voice</span><select data-action="onboarding-setting" data-field="voicePersona">${VOICE_PERSONAS.map(value=>`<option value="${value}" ${draft.settings.voicePersona===value?"selected":""}>${escapeHtml(VOICE_PERSONA_LABELS[value])}</option>`).join("")}</select><small>Recommended for ${escapeHtml(draft.profile.tone)}: ${escapeHtml(recommendedVoice || "current voice")}</small></label><label class="toggle-row"><span><b>Allow earned coaching inside the app</b><small>No OS notifications in this founder build.</small></span><input type="checkbox" data-action="onboarding-toggle" data-field="proactive" ${draft.profile.proactive?"checked":""}></label></div><div class="tone-preview" data-tone="${escapeHtml(draft.profile.tone.toLowerCase())}"><span class="trainer-orb small"><i></i></span><p><b>${escapeHtml(draft.profile.tone)} preview</b><small>${draft.profile.tone === "Supportive" ? "We’ll lower the size of today’s session without judging the day." : draft.profile.tone === "Strict" ? "The standard stays clear. We’ll choose a smaller valid session and complete it." : draft.profile.tone === "Competitive" ? "Beat your verified baseline: one honest session, no fake hype." : "Here’s the constraint, the useful option, and what changes if you approve it."}</small></p></div></div>`;
}

function boundaryStep(draft) {
  return `<div class="onboarding-step"><span class="eyebrow">CLEAR BOUNDARIES</span><h1>Useful, honest, and still in your control.</h1><p>Review what this founder build can and cannot do before entering the app.</p><div class="boundary-list"><article>${icon("check")}<span><b>Workout data stays local</b><small>Plans, sets, preferences, and progress live in this browser.</small></span></article><article>${icon("check")}<span><b>Coach gets bounded text context</b><small>Only ordinary low-sensitivity codes and text go through Symbio’s server.</small></span></article><article>${icon("check")}<span><b>You approve every plan change</b><small>The model writes display copy; it cannot activate a plan or write memory.</small></span></article><article>${icon("close")}<span><b>Not medical care or form assessment</b><small>No diagnosis, rehabilitation, medication, emergency care, or vision-based form correction.</small></span></article></div><label class="consent-row"><input type="checkbox" data-action="onboarding-consent" ${draft.consent?"checked":""}><span><b>I understand this is a private synthetic founder build.</b><small>I will not enter medical records, medications, measurements, credentials, identifiers, or private health information.</small></span></label></div>`;
}

export function renderOnboarding({step,draft}) {
  const pages = [goalStep,scheduleStep,relationshipStep,boundaryStep];
  return `<section class="onboarding-screen"><header><button class="icon-only" data-action="exit-onboarding" aria-label="Exit onboarding">${icon("close")}</button><div class="onboarding-progress"><span style="width:${(step+1)*25}%"></span></div><small>Step ${step+1} of 4</small></header><main>${pages[step](draft)}</main><footer>${button({label:"Back",action:"onboarding-back",variant:"quiet",disabled:step===0})}${button({label:step===3?"Enter FitCoach":"Continue",action:"onboarding-next",variant:"primary",disabled:step===3&&!draft.consent})}</footer></section>`;
}
